// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_option from "rescript/lib/es6/js_option.js"

var listeners = new Map()

function scrollRunner(param) {
	var v = scrollY
	listeners.forEach(function (listener, _key) {
		listener(v)
	})
}

function onScroll(l, immediate) {
	var id = listeners.size
	var opts = {
		contents: undefined,
	}
	if (!listeners.has(id)) {
		listeners.set(id, l)
		if (immediate) {
			l(scrollY)
		}
		if (id === 0) {
			var o = {
				passive: true,
				capture: false,
			}
			opts.contents = Js_option.some(o)
			addEventListener("scroll", scrollRunner, o)
		}
	}
	return function (removeGlobal) {
		listeners.delete(id)
		if (removeGlobal) {
			return removeEventListener(
				"scroll",
				scrollRunner,
				Js_option.getExn(opts.contents),
			)
		}
	}
}

export { onScroll }
/* listeners Not a pure module */
